---
- name: Download imgcat
  get_url:
    url: https://iterm2.com/utilities/imgcat
    dest: '{{ansible_env.HOME}}/.local/bin/imgcat'
    mode: '0755'
    

- name: Download codebuild local
  get_url:
    url: https://raw.githubusercontent.com/aws/aws-codebuild-docker-images/master/local_builds/codebuild_build.sh
    dest: '{{ansible_env.HOME}}/.local/bin/codebuild'
    mode: '0755'