---
- hosts: localhost
  roles:
    - scripts
    - bfg
    - aws
    - mac_apps
    - brew
    - cargo
    # - setup_jupyter_kernels
    - zsh_setup
    - git_setup
    - role: spark
      spark_version: 3.1.2