---
- hosts: localhost
  roles:
    - scripts
    - bfg
    - aws
    - role: 'brew'
      tags: 'brew'
    - cargo
    # - setup_jupyter_kernels
    - role: 'zsh_setup'
      tags: 'zsh_setup'
    - git_setup
    - role: spark
      spark_version: 3.1.2
    - role: yarn
      tags: 'yarn'
    - role: solana
      tags: 'solana'