---
- hosts: my_servers
  roles:
    - {role: bfg, tags: bfgt}
    - role: apt
      tags: apt
    - role: git_setup
      tags: git
    - role: ansible-role-oh-my-zsh  # gantsign.oh-my-zsh
      tags: oh-my-zsh
      users:
        - username: mark
          oh_my_zsh:
          theme: agnoster
          plugins:
            - git
            - mvn
            - bundler
            - sdotenv
            - osx
            - rake
            - rbenv
            - ruby
            - zsh-autosuggestions
            - zsh-syntax-highlighting
    # - role: ansible-role-java  # lean_delivery.java
    #   tags: java11
    #   transport: repositories
    #   java_major_version: 11
    # - role: ansible-role-java  # lean_delivery.java
    #   tags: java8
    #   transport: repositories
    #   java_major_version: 8
    
    - role: ansible-role-golang  # gantsign.golang
      tags: golang
      golang_gopath: '$HOME/go'
      become: true
    - role: ansible-role-swift  # alexcoppe.swift
      swift_install_directory: /opt/
      tags: swift
      become: true
    - role: python
    - role: ansible-role-docker  # geerlingguy.docker
      tags: docker
      become: true
      vars:
        docker_install_compose: false
        docker_apt_ignore_key_error: false
        docker_users: ['mark']