---
- hosts: localhost
  roles:
    - scripts
    - bfg
    - aws
    - role: 'brew'
      tags: 'brew'
    - role: cargo
      tags: 'cargo'
    - role: node
      tags: 'node'
    # - setup_jupyter_kernels
    - role: 'zsh_setup'
      tags: 'zsh_setup'
    - role: git_setup
      tags: 'git_setup'
    - role: spark
      spark_version: 3.1.2
      tags: 'spark'
    - role: solana
      tags: 'solana'