---
- hosts: localhost
  roles:
    - scripts
    - bfg
    - aws
    - role: 'brew'
      tags: 'brew'
    - cargo
    # - setup_jupyter_kernels
    - role: 'zsh_setup'
      tags: 'zsh_setup'
    - git_setup
    - role: spark
      spark_version: 3.2.1
      tags: 'spark'
    - role: 'shiftit'
      tags: 'shiftit'
    - role: 'atom'
      tags: 'atom'
    - role: node
      tags: 'node'
    - role: solana
      tags: 'solana'