- name: install packages using apt
  apt:
    name: "{{packages}}"
    update_cache: yes
    state: latest
  become: true


- name: Remove useless packages from the cache
  apt:
    autoclean: yes

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes
