---

- name: install anaconda
  include_role:
    name: ansible-anaconda  # andrewrothstein.anaconda
  # vars:
    # anaconda_install_packages: "{{conda_packages}}"

- name: install python packages
  shell: export PATH="/usr/local/anaconda/bin:$PATH" && source activate base && pip install {{item}}
  args:
    executable: /bin/bash
  with_items: "{{packages}}"
