---

- name: get latest shift-it download url
  shell: curl -sL https://api.github.com/repos/fikovnik/ShiftIt/releases/latest | jq -r ".zipball_url"
  register: shiftit_download_url

- name: get latest shift-it version
  shell: curl -sL https://api.github.com/repos/fikovnik/ShiftIt/releases/latest | jq -r ".name"
  register: shiftit_version

- name: download shift-it
  get_url:
    url: '{{shiftit_download_url.stdout}}'
    dest: '{{ansible_env.HOME}}/Downloads/ShiftIt-{{shiftit_version.stdout}}.zip'

- name: unzip shift-it
  ansible.builtin.unarchive:
    src: '{{ansible_env.HOME}}/Downloads/ShiftIt-{{shiftit_version.stdout}}.zip'
    dest: /Applications/

- name: cleanup shiftit download
  file:
    state: absent
    path: '{{ansible_env.HOME}}/Downloads/ShiftIt-{{shiftit_version.stdout}}.zip'
