---
###########################################################################
## Install Fonts
###########################################################################
- name: clone powerline fonts
  git:
    repo: 'https://github.com/powerline/fonts.git'
    dest: '{{ansible_env.HOME}}/Documents/iterm_settings/fonts'

- name: install powerline fonts
  command: '{{ansible_env.HOME}}/Documents/iterm_settings/fonts/install.sh'
  args:
    chdir: '{{ansible_env.HOME}}/Documents/iterm_settings/fonts'

- name: download range mono font
  get_url:
    url: https://github.com/leafo/moonscript-javascript/raw/master/fonts/range-mono-medium-webfont.ttf
    dest: /Library/Fonts/range-mono-medium-webfont.ttf

###########################################################################
## Download Color Schemes
###########################################################################
- name: download the color schemes for iTerm2
  git:
    repo: 'https://github.com/mbadolato/iTerm2-Color-Schemes.git'
    dest: '{{ansible_env.HOME}}/Documents/iterm_settings/iTerm2-Color-Schemes'

- name: download material design for iTerm2
  git:
    repo: 'https://github.com/MartinSeeler/iterm2-material-design.git'
    dest: '{{ansible_env.HOME}}/Documents/iterm_settings/iterm2-material-design'

- name: Create cobalt2 color scheme directory
  file:
    path: '{{ansible_env.HOME}}/Documents/iterm_settings/Cobalt2-iterm'
    state: directory

- name: download cobalt2 color scheme for iTerm2
  get_url:
    url: https://raw.githubusercontent.com/wesbos/Cobalt2-iterm/master/cobalt2.itermcolors
    dest: '{{ansible_env.HOME}}/Documents/iterm_settings/Cobalt2-iterm/cobalt2.itermcolors'

###########################################################################
## Install oh-my-zsh
###########################################################################
- name: Check if oh-my-zsh is already installed
  stat:
    path: '{{ansible_env.HOME}}/.oh-my-zsh'
  register: oh_my_zsh_check

- name: install oh-my-zsh
  shell: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  when:
    - not oh_my_zsh_check.stat.exists

# install auto suggestions script
- name: clone zsh-autosuggestions repo
  git:
    repo: 'https://github.com/zsh-users/zsh-autosuggestions'
    dest: '{{ansible_env.HOME}}/.oh-my-zsh/custom/plugins/zsh-autosuggestions'

- name: clone zsh-syntax-highlighting repo
  git:
    repo: 'https://github.com/zsh-users/zsh-syntax-highlighting.git'
    dest: '{{ansible_env.HOME}}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting'

- name: Install pure-prompt
  npm:
    name: pure-prompt
    global: yes

- name: download cobalt2 oh-my-zsh theme
  get_url:
    url: https://raw.githubusercontent.com/wesbos/Cobalt2-iterm/master/cobalt2.zsh-theme
    dest: '{{ansible_env.HOME}}/.oh-my-zsh/themes/cobalt2.zsh-theme'

###########################################################################
## Linking any profile and rc files
###########################################################################
- name: Check if ~/.zshrc already exists
  stat:
    path: '{{ansible_env.HOME}}/.zshrc'
  register: zshrc_check

- name: Move ~/.zshrc to ~/.zshrc.old
  command: 'mv {{ansible_env.HOME}}/.zshrc {{ansible_env.HOME}}/.zshrc.old'
  when: zshrc_check.stat.exists

- name: Create hard for .zshrc
  ansible.builtin.file:
    src: '{{ansible_env.HOME}}/useful_scripts/.zshrc'
    dest: '{{ansible_env.HOME}}/.zshrc'
    state: hard

- name: Check if ~/.zprofile already exists
  stat:
    path: '{{ansible_env.HOME}}/.zprofile'
  register: zprofile_check

- name: Move ~/.zprofile to ~/.zprofile.old
  command: 'mv {{ansible_env.HOME}}/.zprofile {{ansible_env.HOME}}/.zprofile.old'
  when: zprofile_check.stat.exists

- name: Create hard for .zprofile
  ansible.builtin.file:
    src: '{{ansible_env.HOME}}/useful_scripts/.zprofile'
    dest: '{{ansible_env.HOME}}/.zprofile'
    state: hard