---
- name: Check if Homebrew is already installed
  stat:
    path: /usr/local/bin/brew
  register: homebrew_check

- name: install homebrew
  script: install_homebrew.sh
  when:
    - not homebrew_check.stat.exists

- name: ensure homebrew is updated
  homebrew:
    state: latest
    update_homebrew: yes
