---
- name: add taps
  homebrew_tap:
    name: "{{item}}"
  with_items: "{{taps}}"

- name: ensure homebrew is updated
  homebrew:
    state: latest
    update_homebrew: yes

- name: start installing homebrew applications
  homebrew:
    name: "{{applications}}"
    state: latest