---
# - name: add taps
#   homebrew_tap:
#     name: "{{item}}"
#   with_items: "{{taps}}"

- name: install cask applications
  homebrew_cask:
    name: "{{item}}"
    state: present
  with_items: "{{cask_applications}}"

- name: start installing homebrew applications
  homebrew:
    name: "{{applications}}"
    state: latest