---
- name: install java
  homebrew_cask:
    name: "{{item}}"
    state: present
  with_items: "{{cask_applications}}"

- name: start installing homebrew applications
  homebrew:
    name: "{{item}}"
    state: latest
  with_items: "{{applications}}"

- name: install homebrew packages with options
  homebrew:
    name: "{{item}}"
    state: latest
    install_options: with-default-names
  with_items: "{{applications_with_default_names}}"

- name: install vim
  homebrew:
    name: vim
    state: latest
    install_options: override-system-vi

- name: install macvim
  homebrew:
    name: macvim
    state: latest
    install_options: override-system-vi,custom-system-icons

- name: install wdiff
  homebrew:
    name: wdiff
    state: latest
    install_options: with-gettext
