---


- name: download atom
  get_url:
    url: https://atom.io/download/mac
    dest: '{{ansible_env.HOME}}/Downloads/atom-mac.zip'

- name: unzip atom
  ansible.builtin.unarchive:
    src: '{{ansible_env.HOME}}/Downloads/atom-mac.zip'
    dest: /Applications/

- name: cleanup atom download
  file:
    state: absent
    path: '{{ansible_env.HOME}}/Downloads/atom-mac.zip'

