---

    - name: download julia
      include_role:
        name: https://julialang-s3.julialang.org/bin/linux/x64/1.3/julia-{{ julia_version }}-linux-x86_64.tar.gz
    
    - name: install python packages
      pip:
        name: "{item}"
      with_items: "{{packages}}"
    