---

- name: test su
  local_action: command whoami
  register: username_on_the_host
  become: yes
  become_user: root
  become_method: su

- debug: var=username_on_the_host

- name: Install sudo as root
  command: apt update && apt install sudo -y
  become: yes
  become_user: root
  become_method: su

- name: Add user to sudo group
  command: adduser {{sudo_user}} sudo
  become: yes
  become_method: su